<a href="/" class="btn ">home</a>
<a href="/user/dashboard" class="btn">profile</a>
<a href="/user/logout" class="btn">logout</a>
<hr>
<div class="col-lg-12 text-center mt-5">
    <h1>Search for your favorite music</h1>
</div>
<div class="col-md-4 offset-md-4 mt-5 border border-success pt-3">
    <div class="input-group mb-3">
        <form action="/spotify/search" method="get">


            <div class="input-group-append">
                <input type="text" name='q' class="form-control" placeholder="Search ......" aria-label="Recipient's username" required>
                <button type="submit"><i class="fa fa-search"></i></button>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="album" name='filter'>
                <label class="form-check-label" for="filter">
                    album
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="artist" name='artist'>
                <label class="form-check-label" for="filter">
                    artist
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="playlist" name='playlist'>
                <label class="form-check-label" for="filter">
                    playlist
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="track" name='track'>
                <label class="form-check-label" for="filter">
                    track
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="show" name='show'>
                <label class="form-check-label" for="filter">
                    show
                </label>
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="episode" name='episode'>
                <label class="form-check-label" for="filter">
                    episode
                </label>
            </div>
        </form>


    </div>
</div>