<a href="/" class="btn ">home</a>
<a href="/user/dashboard" class="btn">profile</a>
<a href="/spotify/player" class="btn">player</a>
<a href="/user/logout" class="btn">logout</a>
<hr>
<div class='container'>

    <h1 class='text-center p-3 '>player api </h1>
    <p class='text-center text-danger'>(play a song in your connected account to check) </p>
    <hr>
    <?php if ($current['name']) { ?>
        <div class="row">
            <div class="col-5">
                <h1>Currently Playing</h1>
                <div class="card" style="width: 18rem;">
                    <img src="<?php echo $current['album']['images'][1]['url'];  ?>" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title fw-bold"><?php echo $current['name'];  ?></h5>
                        <h6 class="card-subtitle mb-2 text-muted"><?php echo $current['album']['artists'][0]['name'];  ?></h6>
                        <a href="<?php echo $current["external_urls"]["spotify"] ?>" target="_blank" class="btn"><i class="fab fa-github"></i> View More </a>
                    </div>
                </div>
            </div><?php } ?>
        <div class="col-4">
            <h1>
                Current Devices
            </h1>

            <?php
            foreach ($devices as $key => $value) {
                echo "<p>" . $value['name'] . "</p>";
            }
            ?>
        </div>
        </div>

</div>